name: Build Executables

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: windows-latest
            platform: windows
            extension: .exe
          - os: macos-latest
            platform: macos
            extension: ''
          - os: ubuntu-latest
            platform: linux
            extension: ''

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install PySide6 pint requests pyinstaller Pillow

    - name: Build executable (Windows)
      if: matrix.platform == 'windows'
      run: |
        pyinstaller --onefile --windowed --icon=calcforge.ico --name=CalcForge calcforge.py

    - name: Build executable (macOS)
      if: matrix.platform == 'macos'
      run: |
        pyinstaller --onedir --windowed --icon=calcforge.ico --name=CalcForge calcforge.py

    - name: Build executable (Linux)
      if: matrix.platform == 'linux'
      run: |
        pyinstaller --onefile --name=CalcForge calcforge.py

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: CalcForge-${{ matrix.platform }}
        path: |
          dist/CalcForge${{ matrix.extension }}
          dist/CalcForge.app/
        if-no-files-found: ignore

  release:
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    
    steps:
    - name: Download all artifacts
      uses: actions/download-artifact@v4
      
    - name: Create macOS archive
      run: |
        cd CalcForge-macos
        if [ -d "CalcForge.app" ]; then
          zip -r CalcForge-macos.zip CalcForge.app
        fi
        cd ..
    
    - name: Rename files for release
      run: |
        # Create a releases directory
        mkdir -p releases
        
        # Copy and rename files with platform labels
        cp CalcForge-windows/CalcForge.exe releases/CalcForge-Windows.exe
        cp CalcForge-macos/CalcForge-macos.zip releases/CalcForge-macOS.zip
        cp CalcForge-linux/CalcForge releases/CalcForge-Linux
      
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          releases/CalcForge-Windows.exe
          releases/CalcForge-macOS.zip
          releases/CalcForge-Linux
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 